src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement_End_Date__c</fullName>
        <description>Agreement End Date</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Agreement_Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agreement Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements (Agreement Partner)</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreement_Stage__c</fullName>
        <label>Agreement Stage</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PI Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OU Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Routed to OCC for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OCC Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OCC Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OU Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPO Signed/Agreement Finalized</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Agreement_Start_Date__c</fullName>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <picklist>
            <picklistValues>
                <fullName>Agreement In Process</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Agreement_Title__c</fullName>
        <label>Agreement Title</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agreement_Type__c</fullName>
        <label>Agreement Type</label>
        <picklist>
            <picklistValues>
                <fullName>CRADA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Transfer Agreement (DTA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Material Transfer Agreement (MTA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Disclosure Agreement (NDA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Animal_subject_Inclusion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Animal subject Inclusion</description>
        <label>Animal subject Inclusion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Human_Subjects_Inclusion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Human Subjects Inclusion</description>
        <label>Human Subjects Inclusion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>International_Office_IAAO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>International Office (IAAO)</description>
        <label>International Office (IAAO)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NIST_OU__c</fullName>
        <formula>TEXT(NIST_PI__r.NIST_OU__c)</formula>
        <label>NIST OU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NIST_PI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NIST PI</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Staff/Associate</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Agreements (NIST PI)</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patent_Office__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patent Officer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status_Animal_Sub_incl__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Animal_subject_Inclusion__c</controllingField>
            <picklistValues>
                <fullName>Notification Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Memo Received</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Human_Sub_Inc__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Human_Subjects_Inclusion__c</controllingField>
            <picklistValues>
                <fullName>Notification Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Memo Received</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_International_Office__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>International_Office_IAAO__c</controllingField>
            <picklistValues>
                <fullName>Notification Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Memo Received</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Patent_Office__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Patent_Office__c</controllingField>
            <picklistValues>
                <fullName>Notification Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Memo Received</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_US_Trade_Rep__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>US_Trade_Representative__c</controllingField>
            <picklistValues>
                <fullName>Notification Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Memo Received</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>US_Trade_Representative__c</fullName>
        <defaultValue>false</defaultValue>
        <description>US Trade Representative</description>
        <label>US Trade Representative</label>
        <type>Checkbox</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AG-{0000}</displayFormat>
        <label>Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>NIST_OU__c</fullName>
        <description>A list of all of the NIST Operating Units (OU).</description>
        <inlineHelpText>NIST Operating Unit (OU)</inlineHelpText>
        <label>NIST OU</label>
        <picklist>
            <picklistValues>
                <fullName>MEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMNPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MML</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCNR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PML</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Non-NIST Staff/Associate Contact records</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AgreementTriggerHelperTest.cls
@isTest

private class AgreementTriggerHelperTest{

    static testMethod void TestinsertAgreement() {
   
        RecordType recContact = [Select id from RecordType where name = 'Contact'];
        RecordType recStaff = [Select id from RecordType where name = 'Staff/Associate'];
        Account acct = new Account (Name = 'test acct');
        insert acct;
        Contact cont = new Contact (LastName = 'testStaff', Account = acct, RecordTypeid = recStaff.id, NIST_OU__c = 'MEP');
        insert cont;
        System.debug('Account.name: '+acct.name + acct.Id);
    
    

//Create Agreements 
    
    
      
     Agreement__c  a1 = new Agreement__c (
                             Agreement_Partner__c = acct.id, 
                             Agreement_Title__c = 'test title', 
                             Agreement_Start_Date__c = system.today(), 
                             NIST_PI__c = cont.id,
                             Agreement_Type__c = 'CRADA',
                             Agreement_Stage__c = 'New', 
                             Agreement_Status__c = 'Active',
                             Human_Subjects_Inclusion__c = TRUE,
                             Status_Human_Sub_Inc__c = 'Notification Sent',
                             International_Office_IAAO__c = TRUE,
                             Status_International_Office__c = 'Notification Sent',
                             Animal_subject_Inclusion__c = TRUE,
                             Status_Animal_Sub_incl__c = 'Notification Sent'
                                                       );
                                                            
        insert a1;
               
                a1.Agreement_Stage__c = 'OU Approved';  
                a1.Agreement_Status__c = 'Pending Amendment';
                a1.Status_Human_Sub_Inc__c ='Approved';
                a1.Status_International_Office__c ='Approved';
                a1.Status_Animal_Sub_incl__c ='Approved';
                update a1;
                
             Agreement__c  a2 = new Agreement__c (
                             Agreement_Partner__c = acct.id, 
                             Agreement_Title__c = 'test title', 
                             Agreement_Start_Date__c = system.today(), 
                             NIST_PI__c = cont.id,
                             Agreement_Type__c = 'CRADA',
                             Agreement_Stage__c = 'Agreement in Process', 
                             Agreement_Status__c = 'Pending Amendment',
                             Human_Subjects_Inclusion__c = TRUE,
                             Status_Human_Sub_Inc__c = 'Approved',
                             International_Office_IAAO__c = TRUE,
                             Status_International_Office__c = 'Approved',
                             Animal_subject_Inclusion__c = TRUE,
                             Status_Animal_Sub_incl__c = 'Approved'
                                                       );
                                                            
        insert a2;
               
                a2.Agreement_Stage__c = 'PI Approved';  
                a2.Agreement_Status__c = 'Terminated';
                a2.Status_Human_Sub_Inc__c ='Approved';
                a2.Status_International_Office__c ='Approved';
                a2.Status_Animal_Sub_incl__c ='Approved';
                update a2;   
                
             Agreement__c  a3 = new Agreement__c (
                             Agreement_Partner__c = acct.id, 
                             Agreement_Title__c = 'test title', 
                             Agreement_Start_Date__c = system.today(), 
                             NIST_PI__c = cont.id,
                             Agreement_Type__c = 'CRADA',
                             Agreement_Stage__c = 'OU Approved', 
                             Agreement_Status__c = 'Agreement in Process',
                             Human_Subjects_Inclusion__c = TRUE,
                             Status_Human_Sub_Inc__c = 'Memo Received',
                             International_Office_IAAO__c = TRUE,
                             Status_International_Office__c = 'Memo Received',
                             Animal_subject_Inclusion__c = TRUE,
                             Status_Animal_Sub_incl__c = 'Memo Received'
                                                       );
                                                            
        insert a3;
               
                a3.Agreement_Stage__c = 'OU Approved';  
                a3.Agreement_Status__c = 'Expired';
                a3.Status_Human_Sub_Inc__c ='Notification Sent';
                a3.Status_International_Office__c ='Notification Sent';
                a3.Status_Animal_Sub_incl__c ='Notification Sent';
                update a3;   
                
                
                
                Agreement__c  a4 = new Agreement__c (
                             Agreement_Partner__c = acct.id, 
                             Agreement_Title__c = 'test title', 
                             Agreement_Start_Date__c = system.today(), 
                             NIST_PI__c = cont.id,
                             Agreement_Type__c = 'CRADA',
                             Agreement_Stage__c = 'OCC Signed', 
                             Agreement_Status__c = 'Pending Amendment',
                             Human_Subjects_Inclusion__c = TRUE,
                             Status_Human_Sub_Inc__c = 'Notification Sent',
                             International_Office_IAAO__c = TRUE,
                             Status_International_Office__c = 'Notification Sent',
                             Animal_subject_Inclusion__c = TRUE,
                             Status_Animal_Sub_incl__c = 'Notification Sent'
                                                       );
                                                            
        insert a4;
               
                a4.Agreement_Stage__c = 'TPO Signed/Agreement Finalized';  
                a4.Agreement_Status__c = 'Terminated';
                a4.Status_Human_Sub_Inc__c ='Approved';
                a4.Status_International_Office__c ='Approved';
                a4.Status_Animal_Sub_incl__c ='Approved';
                update a4;
                
                Agreement__c  a5 = new Agreement__c (
                             Agreement_Partner__c = acct.id, 
                             Agreement_Title__c = 'test title', 
                             Agreement_Start_Date__c = system.today(), 
                             Agreement_End_Date__c = system.today(),
                             NIST_PI__c = cont.id,
                             Agreement_Type__c = 'CRADA',
                             Agreement_Stage__c = 'OCC Approval', 
                             Agreement_Status__c = 'Canceled',
                             Human_Subjects_Inclusion__c = TRUE,
                             Status_Human_Sub_Inc__c = 'Notification Sent',
                             International_Office_IAAO__c = TRUE,
                             Status_International_Office__c = 'Notification Sent',
                             Animal_subject_Inclusion__c = TRUE,
                             Status_Animal_Sub_incl__c = 'Notification Sent',
                             Patent_Office__c = TRUE,
                             Status_Patent_Office__c = 'Notification Sent',
                             US_Trade_Representative__c = TRUE,
                             Status_US_Trade_Rep__c = 'Notification Sent'
                                                       );
                                                            
        insert a5;
               
                a5.Agreement_Stage__c = 'Partner Signed';  
                a5.Agreement_Status__c = 'Terminated';
                a5.Status_Human_Sub_Inc__c ='Approved';
                a5.Status_International_Office__c ='Approved';
                a5.Status_Animal_Sub_incl__c ='Approved';
                a5.Status_Patent_Office__c = 'Approved';
                a5.Status_US_Trade_Rep__c = 'Memo Received';
                update a5;
                
                Agreement__c  a6 = new Agreement__c (
                             Agreement_Partner__c = acct.id, 
                             Agreement_Title__c = 'test title', 
                             Agreement_Start_Date__c = system.today(), 
                             Agreement_End_Date__c = system.today(),
                             NIST_PI__c = cont.id,
                             Agreement_Type__c = 'CRADA',
                             Agreement_Stage__c = 'TPO Signed/Agreement Finalized', 
                             Agreement_Status__c = 'Canceled',
                             Human_Subjects_Inclusion__c = TRUE,
                             Status_Human_Sub_Inc__c = 'Notification Sent',
                             International_Office_IAAO__c = TRUE,
                             Status_International_Office__c = 'Notification Sent',
                             Animal_subject_Inclusion__c = TRUE,
                             Status_Animal_Sub_incl__c = 'Notification Sent',
                             Patent_Office__c = TRUE,
                             Status_Patent_Office__c = 'Memo Received',
                             US_Trade_Representative__c = TRUE,
                             Status_US_Trade_Rep__c = 'Notification Sent'
                                                       );
                                                            
        insert a6;
               
                a6.Agreement_Stage__c = 'OCC Signed';  
                a6.Agreement_Status__c = 'Canceled';
                a6.Status_Human_Sub_Inc__c ='Memo Received';
                a6.Status_International_Office__c ='Memo Received';
                a6.Status_Animal_Sub_incl__c ='Memo Received';
                a6.Status_Patent_Office__c = 'Notification Sent';
                a6.Status_US_Trade_Rep__c = 'Memo Received';
                update a6;
                           
             
                
        Agreement__c  a7 = new Agreement__c (
                             Agreement_Partner__c = acct.id, 
                             Agreement_Title__c = 'test title', 
                             Agreement_Start_Date__c = system.today(), 
                             Agreement_End_Date__c = system.today(),
                             NIST_PI__c = cont.id,
                             Agreement_Type__c = 'CRADA',
                             Agreement_Stage__c = 'Partner Signed', 
                             Agreement_Status__c = 'Active',
                             Human_Subjects_Inclusion__c = TRUE,
                             Status_Human_Sub_Inc__c = 'Notification Sent',
                             International_Office_IAAO__c = TRUE,
                             Status_International_Office__c = 'Notification Sent',
                             Animal_subject_Inclusion__c = TRUE,
                             Status_Animal_Sub_incl__c = 'Notification Sent',
                             Patent_Office__c = TRUE,
                             Status_Patent_Office__c = 'Notification Sent',
                             US_Trade_Representative__c = TRUE,
                             Status_US_Trade_Rep__c = 'Memo Received'
                                                       );
                                                            
        insert a7;
               
                a7.Agreement_Stage__c = 'OCC Signed';  
                a7.Agreement_Status__c = 'Canceled';
                a7.Status_Human_Sub_Inc__c ='Memo Received';
                a7.Status_International_Office__c ='Memo Received';
                a7.Status_Animal_Sub_incl__c ='Approved';
                a7.Status_Patent_Office__c = 'Approved';
                a7.Status_US_Trade_Rep__c = 'Notification Sent';
                update a7;
                
        Agreement__c  a8 = new Agreement__c (
                             Agreement_Partner__c = acct.id, 
                             Agreement_Title__c = 'test title', 
                             Agreement_Start_Date__c = system.today(), 
                             Agreement_End_Date__c = system.today(),
                             NIST_PI__c = cont.id,
                             Agreement_Type__c = 'CRADA',
                             Agreement_Stage__c = 'OU Signed', 
                             Agreement_Status__c = 'Active',
                             Human_Subjects_Inclusion__c = TRUE,
                             Status_Human_Sub_Inc__c = 'Notification Sent',
                             International_Office_IAAO__c = TRUE,
                             Status_International_Office__c = 'Notification Sent',
                             Animal_subject_Inclusion__c = TRUE,
                             Status_Animal_Sub_incl__c = 'Notification Sent',
                             Patent_Office__c = TRUE,
                             Status_Patent_Office__c = 'Approved',
                             US_Trade_Representative__c = TRUE,
                             Status_US_Trade_Rep__c = 'Notification Sent'
                                                       );
                                                            
        insert a8;
               
                a8.Agreement_Stage__c = 'Routed To OCC For Approval';  
                a8.Agreement_Status__c = 'Canceled';
                a8.Status_Human_Sub_Inc__c ='Memo Received';
                a8.Status_International_Office__c ='Memo Received';
                a8.Status_Animal_Sub_incl__c ='Memo Received';
                a8.Status_Patent_Office__c = 'Memo Received';
                a8.Status_US_Trade_Rep__c = 'Memo Received';
                update a8;                
                
          }
    

}