src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement_Stage__c</fullName>
        <label>Agreement Stage</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PI Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OU Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Routed to OCC for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OCC Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OCC Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OU Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPO Signed/Agreement Finalized</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <picklist>
            <picklistValues>
                <fullName>Agreement In Process</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Animal_Sub_incl__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Animal_subject_Inclusion__c</controllingField>
            <picklistValues>
                <fullName>Notification Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Memo Received</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Human_Sub_Inc__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Human_Subjects_Inclusion__c</controllingField>
            <picklistValues>
                <fullName>Notification Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Memo Received</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_International_Office__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>International_Office_IAAO__c</controllingField>
            <picklistValues>
                <fullName>Notification Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Memo Received</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Patent_Office__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Patent_Office__c</controllingField>
            <picklistValues>
                <fullName>Notification Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Memo Received</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_US_Trade_Rep__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>US_Trade_Representative__c</controllingField>
            <picklistValues>
                <fullName>Notification Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Memo Received</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AG-{0000}</displayFormat>
        <label>Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Snapshot__c.object
<CustomObject>
    <description>This object will be used to record snapshots of changes on other records when needed.</description>
    <fields>
        <fullName>ASI_Approved_Date__c</fullName>
        <description>ASI Approved Date</description>
        <label>ASI Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ASI_Memo_Received_Date__c</fullName>
        <description>ASI Memo Received Date</description>
        <label>ASI Memo Received Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ASI_Notification_Sent_Date__c</fullName>
        <description>ASI Notification Sent Date</description>
        <label>ASI Notification Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_New_Date__c</fullName>
        <label>Agreement New Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_OCC_Approval_Date__c</fullName>
        <label>Agreement OCC Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_OCC_Signed_Date__c</fullName>
        <label>Agreement OCC Signed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_OU_Approved_Date__c</fullName>
        <label>Agreement OU Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_OU_Signed_Date__c</fullName>
        <label>Agreement OU Signed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_PI_Approved_Date__c</fullName>
        <label>Agreement PI Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_Partner_Signed_Date__c</fullName>
        <label>Agreement Partner Signed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_Routed_OCC_Approval_Date__c</fullName>
        <label>Agreement Routed OCC Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_Status_Active_Date__c</fullName>
        <description>Agreement Status Active Date</description>
        <label>Agreement Status Active Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_Status_Canceled_Date__c</fullName>
        <description>Agreement Status Canceled Date</description>
        <label>Agreement Status Canceled Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_Status_Expired_Date__c</fullName>
        <description>Agreement Status Expired Date</description>
        <label>Agreement Status Expired Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_Status_In_Process_Date__c</fullName>
        <description>Agreement Status Agreement In Process Date</description>
        <label>Agreement Status In Process Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_Status_Pending_Amendment_Date__c</fullName>
        <description>Agreement Status Pending Amendment Date</description>
        <label>Agreement Status Pending Amendment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_Status_Terminated_Date__c</fullName>
        <description>Agreement Status Terminated Date</description>
        <label>Agreement Status Terminated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_TPO_Signed_Date__c</fullName>
        <label>Agreement TPO Signed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Snapshots</relationshipLabel>
        <relationshipName>Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HSI_Approved_Date__c</fullName>
        <description>HSI Approved Date</description>
        <label>HSI Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>HSI_Memo_Received_Date__c</fullName>
        <description>HSI Memo Received Date</description>
        <label>HSI Memo Received Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>HSI_Notification_Sent_Date__c</fullName>
        <description>HSI Notification Sent Date</description>
        <label>HSI Notification Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IAAO_Approved_Date__c</fullName>
        <description>IAAO Approved Date</description>
        <label>IAAO Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IAAO_Memo_Received_Date__c</fullName>
        <description>IAAO Memo Received Date</description>
        <label>IAAO Memo Received Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IAAO_Notification_Sent_Date__c</fullName>
        <description>IAAO Notification Sent Date</description>
        <label>IAAO Notification Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Patent_Officer_Approved_Date__c</fullName>
        <description>Patent Officer Approved Date</description>
        <label>Patent Officer Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Patent_Officer_Memo_Received_Date__c</fullName>
        <description>Patent Officer Memo Received Date</description>
        <label>Patent Officer Memo Received Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Patent_Officer_Notification_Sent_Date__c</fullName>
        <description>Patent Officer Notification Sent Date</description>
        <label>Patent Officer Notification Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reference_ID__c</fullName>
        <description>The ID of the record in the original object.</description>
        <label>Reference ID</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Object__c</fullName>
        <label>Reference Object</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USTR_Memo_Received_Date__c</fullName>
        <description>USTR Memo Received Date</description>
        <label>USTR Memo Received Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>USTR_Notification_Sent_Date__c</fullName>
        <description>USTR Notification Sent Date</description>
        <label>USTR Notification Sent Date</label>
        <type>DateTime</type>
    </fields>
    <label>Snapshot</label>
    <nameField>
        <displayFormat>SN-{0000000}</displayFormat>
        <label>Snapshot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgreementTriggerHelper.cls
public with sharing class AgreementTriggerHelper {
    
    public static void insertAgreement (list<Agreement__c> agreements) {
        /*
            Copy the Reference ID, Reference Object, Stage date values to new object.  
            If Stage is not New, add New date as today as well as the correct date value.
        */
        
        Try {
            //System.debug('Total Agreements in insert Trigger: '+agreements.size());
            
            For (Agreement__c a: agreements) {
                //System.debug('i Agreement Info - ID: '+a.id);
                Snapshot__c s = new Snapshot__c();
                s.reference_id__c = a.id;
                s.reference_object__c = 'Agreement';
                s.Agreement__c = a.id;
                
                if (a.Agreement_Stage__c == 'PI Approved') {
                    s.Agreement_PI_Approved_Date__c = system.now(); 
                }
                else if (a.Agreement_Stage__c == 'OU Approved') {
                    s.Agreement_OU_Approved_Date__c = system.now(); 
                }
                else if (a.Agreement_Stage__c == 'Routed to OCC for Approval') {
                    s.Agreement_Routed_OCC_Approval_Date__c = system.now(); 
                }
                else if (a.Agreement_Stage__c == 'OCC Approval') {
                    s.Agreement_OCC_Approval_Date__c = system.now();    
                }
                else if (a.Agreement_Stage__c == 'Partner Signed') {
                    s.Agreement_Partner_Signed_Date__c = system.now();  
                }
                else if (a.Agreement_Stage__c == 'OCC Signed') {
                    s.Agreement_OCC_Signed_Date__c = system.now();  
                }
                else if (a.Agreement_Stage__c == 'OU Signed') {
                    s.Agreement_OU_Signed_Date__c = system.now();   
                }
                else if (a.Agreement_Stage__c == 'TPO Signed/Agreement Finalized') {
                    s.Agreement_TPO_Signed_Date__c = system.now();  
                }
                if (a.Status_Animal_Sub_incl__c == 'Notification Sent') {
                    s.ASI_Notification_Sent_Date__c = system.now();
                }
                else if (a.Status_Animal_Sub_incl__c == 'Memo Received') {
                    s.ASI_Memo_Received_Date__c = system.now();
                 }
                else if (a.Status_Animal_Sub_incl__c == 'Approved') {
                    s.ASI_Approved_Date__c = system.now();
                 }
                if (a.Status_Human_Sub_Inc__c == 'Notification Sent') {
                    s.HSI_Notification_Sent_Date__c = system.now();
                }
                else if (a.Status_Human_Sub_Inc__c == 'Memo Received') {
                    s.HSI_Memo_Received_Date__c = system.now();
                 }
                else if (a.Status_Human_Sub_Inc__c == 'Approved') {
                    s.HSI_Approved_Date__c = system.now();
                 }
                if (a.Status_Patent_Office__c == 'Notification Sent') {
                    s.Patent_Officer_Notification_Sent_Date__c = system.now();
                }
                else if (a.Status_Patent_Office__c == 'Memo Received') {
                    s.Patent_Officer_Memo_Received_Date__c = system.now();
                 }
                else if (a.Status_Patent_Office__c == 'Approved') {
                    s.Patent_Officer_Approved_Date__c = system.now();
                 }
                if (a.Status_International_Office__c == 'Notification Sent') {
                    s.IAAO_Notification_Sent_Date__c = system.now();
                }
                else if (a.Status_International_Office__c == 'Memo Received') {
                    s.IAAO_Memo_Received_Date__c = system.now();
                 }
                else if (a.Status_International_Office__c == 'Approved') {
                    s.IAAO_Approved_Date__c = system.now();
                 }
                if (a.Status_US_Trade_Rep__c == 'Notification Sent') {
                    s.USTR_Notification_Sent_Date__c = system.now();
                }
                else if (a.Status_US_Trade_Rep__c == 'Memo Received') {
                    s.USTR_Memo_Received_Date__c = system.now();
                 }
                
                if (a.Agreement_Status__c == 'Agreement In Process') {
                    s.Agreement_Status_In_Process_Date__c =system.now();
                }
                else if (a.Agreement_Status__c == 'Active'){
                    s.Agreement_Status_Active_Date__c = system.now();
                }
                else if (a.Agreement_Status__c == 'Pending Amendment'){
                    s.Agreement_Status_Pending_Amendment_Date__c = system.now(); 
                }
                /* else if (a.Agreement_Status__c == 'Canceled'){
                    s.Agreement_Status_Canceled_Date__c = system.now();
                }
                 else if (a.Agreement_Status__c == 'Expired'){
                    s.Agreement_Status_Expired_Date__c = system.now();
                }
                else if (a.Agreement_Status__c == 'Terminated'){
                    s.Agreement_Status_Terminated_Date__c = system.now();
                }
                 */
                                
                s.Agreement_New_Date__c = System.now();
                insert s;
            }
        }
        catch (Exception e) {
            System.debug ('i Agreement Trigger Helper Error: '+e);
        }
    }
    
    public static void updateAgreement (list<Agreement__c> newAgreements, list<Agreement__c> oldAgreements) {
        /*  
            Look up the associated Snapshot by Reference ID.  Update the correct Date field based on saved Status value.
        */
        
        List <Snapshot__c> snaps = new List <Snapshot__c> ();
        Set<Id> agreementIDs = new Set<Id>();
        
        For (Agreement__c ag: newAgreements) {
            agreementIDs.add(ag.ID); 
        } 
        
        if (newAgreements.size() > 0) {
            snaps = [Select id, reference_id__c, reference_object__c, Agreement_PI_Approved_Date__c,Agreement_OU_Approved_Date__c,
             Agreement_New_Date__c, Agreement_Routed_OCC_Approval_Date__c, Agreement_OCC_Approval_Date__c, 
            Agreement_Partner_Signed_Date__c, Agreement_OCC_Signed_Date__c, Agreement_OU_Signed_Date__c,
            Agreement_TPO_Signed_Date__c, ASI_Approved_Date__c,ASI_Memo_Received_Date__c,ASI_Notification_Sent_Date__c,
            HSI_Approved_Date__c,HSI_Memo_Received_Date__c,HSI_Notification_Sent_Date__c,
            IAAO_Approved_Date__c,IAAO_Memo_Received_Date__c,IAAO_Notification_Sent_Date__c,
            Patent_Officer_Approved_Date__c,Patent_Officer_Memo_Received_Date__c,Patent_Officer_Notification_Sent_Date__c,
            USTR_Memo_Received_Date__c,USTR_Notification_Sent_Date__c,
                     Agreement_Status_In_Process_Date__c,Agreement_Status_Active_Date__c,Agreement_Status_Pending_Amendment_Date__c,
                     Agreement_Status_Canceled_Date__c,Agreement_Status_Expired_Date__c,Agreement_Status_Terminated_Date__c
                     from Snapshot__c  where reference_id__c in: agreementIDs];
            }
        
        Try {
            //System.debug('u Total Agreements in Trigger: '+newAgreements.size());
            
            For (Agreement__c a: newAgreements) {
                //System.debug('u Agreement Info - ID: '+a.id);
                
                For (Snapshot__c s: snaps) {
                    //System.debug('u Snapshot Info - ID: '+a.id);
                    
                    Agreement__c oldAgree = new Agreement__c ();
                    
                    For (Agreement__c ao: oldAgreements){
                        if (a.id == ao.id) {
                            oldAgree = ao;
                        }
                    }
                     
                    if ((a.id == s.reference_id__c) && ((a.Agreement_Stage__c != oldAgree.Agreement_Stage__c) || 
                                                        (a.Agreement_Status__c != oldAgree.Agreement_Status__c) ||
                                                        (a.Status_Animal_Sub_incl__c != oldAgree.Status_Animal_Sub_incl__c)||
                                                        (a.Status_Human_Sub_Inc__c != oldAgree.Status_Human_Sub_Inc__c) ||
                                                        (a.Status_Patent_Office__c != oldAgree.Status_Patent_Office__c)||
                                                        (a.Status_International_Office__c != oldAgree.Status_International_Office__c)||
                                                        (a.Status_US_Trade_Rep__c != oldAgree.Status_US_Trade_Rep__c))){
                            if (a.Agreement_Stage__c == 'New') {
                                s.Agreement_New_Date__c = System.now();
                            }
                            else if (a.Agreement_Stage__c == 'PI Approved') {
                                s.Agreement_PI_Approved_Date__c = system.now(); 
                            }
                            else if (a.Agreement_Stage__c == 'OU Approved') {
                                s.Agreement_OU_Approved_Date__c = system.now(); 
                            }
                            else if (a.Agreement_Stage__c == 'Routed to OCC for Approval') {
                                s.Agreement_Routed_OCC_Approval_Date__c = system.now(); 
                            }
                            else if (a.Agreement_Stage__c == 'OCC Approval') {
                                s.Agreement_OCC_Approval_Date__c = system.now();    
                            }
                            else if (a.Agreement_Stage__c == 'Partner Signed') {
                                s.Agreement_Partner_Signed_Date__c = system.now();  
                            }
                            else if (a.Agreement_Stage__c == 'OCC Signed') {
                                s.Agreement_OCC_Signed_Date__c = system.now();  
                            }
                            else if (a.Agreement_Stage__c == 'OU Signed') {
                                s.Agreement_OU_Signed_Date__c = system.now();   
                            }
                            else if (a.Agreement_Stage__c == 'TPO Signed/Agreement Finalized') {
                                s.Agreement_TPO_Signed_Date__c = system.now();  
                            }
                            
                            if (a.Status_Animal_Sub_incl__c == 'Notification Sent') {
                                s.ASI_Notification_Sent_Date__c = system.now();
                            }
                            else if (a.Status_Animal_Sub_incl__c == 'Memo Received') {
                                s.ASI_Memo_Received_Date__c = system.now();
                            }
                            else if (a.Status_Animal_Sub_incl__c == 'Approved') {
                                s.ASI_Approved_Date__c = system.now();
                            }
                            
                            if (a.Status_Human_Sub_Inc__c == 'Notification Sent') {
                                s.HSI_Notification_Sent_Date__c = system.now();
                            }
                            else if (a.Status_Human_Sub_Inc__c == 'Memo Received') {
                               s.HSI_Memo_Received_Date__c = system.now();
                            }
                            else if (a.Status_Human_Sub_Inc__c == 'Approved') {
                               s.HSI_Approved_Date__c = system.now();
                            }
                            
                            if (a.Status_Patent_Office__c == 'Notification Sent') {
                                s.Patent_Officer_Notification_Sent_Date__c = system.now();
                            }
                            else if (a.Status_Patent_Office__c == 'Memo Received') {
                                s.Patent_Officer_Memo_Received_Date__c = system.now();
                            }
                            else if (a.Status_Patent_Office__c == 'Approved') {
                                s.Patent_Officer_Approved_Date__c = system.now();
                            }
                            
                            if (a.Status_International_Office__c == 'Notification Sent') {
                                s.IAAO_Notification_Sent_Date__c = system.now();
                            }
                            else if (a.Status_International_Office__c == 'Memo Received') {
                               s.IAAO_Memo_Received_Date__c = system.now();
                            }
                            else if (a.Status_International_Office__c == 'Approved') {
                                s.IAAO_Approved_Date__c = system.now();
                            }
                            
                            if (a.Status_US_Trade_Rep__c == 'Notification Sent') {
                                s.USTR_Notification_Sent_Date__c = system.now();
                            }
                            else if (a.Status_US_Trade_Rep__c == 'Memo Received') {
                                s.USTR_Memo_Received_Date__c = system.now();
                            }
                    
                            if (a.Agreement_Status__c == 'Agreement In Process') {
                                s.Agreement_Status_In_Process_Date__c =system.now();
                            }
                            else if (a.Agreement_Status__c == 'Active'){
                                s.Agreement_Status_Active_Date__c = system.now();
                            }
                            else if (a.Agreement_Status__c == 'Pending Amendment'){
                                s.Agreement_Status_Pending_Amendment_Date__c = system.now(); 
                            }
                             else if (a.Agreement_Status__c == 'Canceled'){
                                s.Agreement_Status_Canceled_Date__c = system.now();
                            }
                            else if (a.Agreement_Status__c == 'Expired'){
                                s.Agreement_Status_Expired_Date__c = system.now();
                            }
                            else if (a.Agreement_Status__c == 'Terminated'){
                                s.Agreement_Status_Terminated_Date__c = system.now();
                            } 
                        
                        }

                    update s;
                    }
                }
                
            }
        
        catch (Exception e) {
            System.debug ('u Agreement Trigger Helper Error: '+e);
        }
    }   
    
}