src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement_Stage__c</fullName>
        <label>Agreement Stage</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PI Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OU Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Routed to OCC for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OCC Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OCC Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OU Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPO Signed/Agreement Finalized</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <picklist>
            <picklistValues>
                <fullName>Agreement In Process</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>AG-{0000}</displayFormat>
        <label>Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CRADA_Tracker.cls
public class CRADA_Tracker {
    private final Agreement__c agreement;
    public Agreement__c agree;
    public StaticResource trackerImage;
    List<StaticResource> docs;
    String namespace;
    
    public CRADA_Tracker (ApexPages.StandardController stdController) {
        this.agreement = (Agreement__c)stdController.getRecord();
        System.debug('agreement.page.id: ' + ApexPages.currentPage().getParameters().get('id'));
        agree = [Select ID, Agreement_Stage__c, Agreement_Status__c from Agreement__c where id =: ApexPages.currentPage().getParameters().get('id')];
        System.debug('Agreement id: ' +agreement.id);
    }
    
    /* public Agreement__c getAgreement() {
        return agreement;
    } */
    
    public String getTrackerImage() {
        if (agree.Agreement_Stage__c == 'New' && agree.Agreement_Status__c != 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_01'];
        } 
        else if (agree.Agreement_Stage__c == 'PI Approved' && agree.Agreement_Status__c != 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_02'];
        }
        else if (agree.Agreement_Stage__c == 'OU Approved' && agree.Agreement_Status__c != 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_03'];
        }
        else if (agree.Agreement_Stage__c == 'Routed to OCC for Approval' && agree.Agreement_Status__c != 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_04'];
        }
        else if (agree.Agreement_Stage__c == 'OCC Approval' && agree.Agreement_Status__c != 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_05'];
        }
        else if (agree.Agreement_Stage__c == 'Partner Signed' && agree.Agreement_Status__c != 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_06'];
        }
        else if (agree.Agreement_Stage__c == 'OCC Signed' && agree.Agreement_Status__c != 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_07'];
        }
        else if (agree.Agreement_Stage__c == 'OU Signed' && agree.Agreement_Status__c != 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_08'];
        }
        else if (agree.Agreement_Stage__c == 'TPO Signed/Agreement Finalized' && agree.Agreement_Status__c != 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_09'];
        }
        
        //Canceled Codes
        else if (agree.Agreement_Stage__c == 'New' && agree.Agreement_Status__c == 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_01C'];
        } 
        else if (agree.Agreement_Stage__c == 'PI Approved' && agree.Agreement_Status__c == 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_02C'];
        }
        else if (agree.Agreement_Stage__c == 'OU Approved' && agree.Agreement_Status__c == 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_03C'];
        }
        else if (agree.Agreement_Stage__c == 'Routed to OCC for Approval' && agree.Agreement_Status__c == 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_04C'];
        }
        else if (agree.Agreement_Stage__c == 'OCC Approval' && agree.Agreement_Status__c == 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_05C'];
        }
        else if (agree.Agreement_Stage__c == 'Partner Signed' && agree.Agreement_Status__c == 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_06C'];
        }
        else if (agree.Agreement_Stage__c == 'OCC Signed' && agree.Agreement_Status__c == 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_07C'];
        }
        else if (agree.Agreement_Stage__c == 'OU Signed' && agree.Agreement_Status__c == 'Canceled') {
           docs = [select id, name from StaticResource where name = 'CRADA_Tracker_08C'];
        }
        else {
            docs = [select id, name from StaticResource where name = 'CRADA_Tracker_10'];
        }
        
        if (docs.size()==1) {
            trackerImage = docs[0];
            return trackerImage.name;
        } else return '';
    }
     
}