src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <controllingField>Responding_Office__c</controllingField>
            <picklistValues>
                <fullName>System Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Enhancements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outlook Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Upload</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licensing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SBIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Location-Based Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Safety Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User Interface</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mission Critical Voice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMR to LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prizes and Challenges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Orders (Standard Reference Materials)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer and IT Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NIST Publications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calibration Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scientific and Technical Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standards Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Responding_Office__c</fullName>
        <description>Office to direct the request.</description>
        <inlineHelpText>Office to direct the request.</inlineHelpText>
        <label>Responding Office</label>
        <picklist>
            <picklistValues>
                <fullName>CTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - PSCR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - NASCTN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - RFTech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - WND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - NCCOE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - NICE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - NSTIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - CSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calibrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OWM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O&amp;M</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/W2CEmails__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Email ids of SF Opt-out Organizations.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>W2CEmails</label>
</CustomObject>

src/classes/SendW2CEmailHelperTest.cls
@isTest
public class SendW2CEmailHelperTest {
    @testSetup static void dataPrep(){
        List<W2CEmails__c> customSettings = new List<W2CEmails__c>();
        customSettings.add(new W2CEmails__c(Name='Calibrations',Email__c='nistcalibrations@gmail.com'));
        insert customSettings;
    }
    static testMethod void sendEmailTest() {        
        List<Case> caseList = new List<Case>(); 
         ID gRT = [Select id from RecordType where name = 'General Inquiries'].id;
        caseList.add(new Case(RecordTypeId = gRT,Origin='Web', Status='New',SuppliedEmail='nagesh.pawar@gmail.com',  
                          Case_Type__c='Calibration Services',Responding_Office__c='Calibrations',
                              Description = 'Test'));       
        insert caseList;

        List<Case> caseExt = [Select Id ,Origin, Status, SuppliedEmail, Case_Type__c,Responding_Office__c,Description 
                              From Case 
                              where Id = :caseList[0].Id];
        System.assertEquals(1, caseExt.size());
    }
}