src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <controllingField>Responding_Office__c</controllingField>
            <picklistValues>
                <fullName>System Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Enhancements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outlook Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Upload</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licensing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SBIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Location-Based Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Safety Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User Interface</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mission Critical Voice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMR to LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prizes and Challenges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Orders (Standard Reference Materials)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer and IT Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NIST Publications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calibration Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scientific and Technical Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standards Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Responding_Office__c</fullName>
        <description>Office to direct the request.</description>
        <inlineHelpText>Office to direct the request.</inlineHelpText>
        <label>Responding Office</label>
        <picklist>
            <picklistValues>
                <fullName>CTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - PSCR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - NASCTN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - RFTech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - WND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - NCCOE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - NICE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - NSTIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - CSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calibrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OWM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O&amp;M</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/W2CEmails__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Email ids of SF Opt-out Organizations.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>W2CEmails</label>
</CustomObject>

src/classes/SendW2CEmailHelper.cls
/*
 * SendW2CEmailHelper 	- 	sends email to  organization's email ids when Case gets created for SF opt-out Organization, 
 * 							with case information and sets reply-to email id.
 *                     	- 	Uses Email Template
 * Trigger 				- 	CaseTrigger
 * Author : Nagesh Pawar
*/

public class SendW2CEmailHelper {
	public static void sendEmail(List<Case> caseList) {
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>(); 
      	EmailTemplate emailTemp=[SELECT Id,Subject, HtmlValue,body 
                                 FROM EmailTemplate 
                                 WHERE name='ITL Inquiry Email Forward'];
      	
        //Get opt-out offices ids from custom settings W2CEmails
        Map<String,W2CEmails__c> allOrgs = W2CEmails__c.getAll();
        ID fromEmailId;
        for(OrgWideEmailAddress owa : [SELECT id, Address, DisplayName FROM OrgWideEmailAddress]) {            
             if(owa.Address.contains('noreply'))
                 fromEmailId = owa.id;            
         }
      	for ( Case c:caseList) {  
           	if(c.Origin == 'Web' && allOrgs.containsKey(c.Responding_Office__c)){ 
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
                //mail.setTargetObjectId(c.Id);
                String  orgEmail =    W2CEmails__c.getInstance(c.Responding_Office__c).Email__c;
                String[] toAddresses = orgEmail.split(';', 0);   
                String htmlbody= emailTemp.HtmlValue;      
                htmlbody= htmlbody.replace('{!Case.SuppliedEmail}', c.SuppliedEmail);
                htmlbody= htmlbody.replace('{!Case.Description}', c.Description);
                String subjectReason = emailTemp.Subject;
                subjectReason = subjectReason.replace('{!Case.Case_Type__c}', c.Case_Type__c);
                mail.setToAddresses(toAddresses);   
                //set replyto value to customer email id
                mail.setReplyTo(c.SuppliedEmail);
                mail.setSubject(subjectReason);   
                mail.setHtmlBody(htmlbody);
                //mail.setPlainTextBody(emailTemp.body);                
                mail.setTemplateId(emailTemp.Id);
                mail.setOrgWideEmailAddressId(fromEmailId);
                mails.add(mail);
            }
    	}      
        Messaging.SendEmail(mails);    
            
	}    
}