src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Multi_Select_Text__c</fullName>
        <label>Multi Select Text</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Responding_Office__c</fullName>
        <description>Office to direct the request.</description>
        <inlineHelpText>Office to direct the request.</inlineHelpText>
        <label>Responding Office</label>
        <picklist>
            <picklistValues>
                <fullName>CTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - PSCR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - NASCTN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - RFTech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - WND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - NCCOE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - NICE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - NSTIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - CSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calibrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OWM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O&amp;M</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Share_Case_With__c</fullName>
        <label>Share Case With</label>
        <picklist>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - NCCOE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - NICE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - NSTIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITL - CSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - PSCR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - NASCTN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - RFTech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTL - WND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PML</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calibrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MML</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADIIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMNPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baldrige</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCNR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O&amp;M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OWM</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CaseTriggerHelper_New.cls
public with sharing class CaseTriggerHelper_New {





    public static void insertMultiSelectText_New(List<Case> newCases){
        
      Try {
            
           RecordType RcdTypId = [select Id from RecordType where Name = 'General Inquiries' and SobjectType = 'Case'];
        
      Case c1;
      
     if (c1.RecordTypeId==RcdTypId.id) {
           
           
        For (case c: newCases) {
            
                
           if (c.Share_Case_With__c == null) {
            c.Share_Case_With__c = c.Responding_Office__c;
          }           
           else {
             c.Share_Case_With__c +=';'+ c.Responding_Office__c;
           }
           
           c.Multi_Select_Text__c = c.Share_Case_With__c;
           
           }
           
         }
            
            }  
      Catch (Exception e) {
        System.debug('CaseTriggerHelper Error: '+e);
                 
      }
  }
 
  public static void updateMultiSelectText(List<Case> newCases, List<Case> oldCases){
        
      Try {
      
      RecordType RcdTypId = [select Id from RecordType where Name = 'General Inquiries' and SobjectType = 'Case'];
        
      Case c1;
      
     if (c1.RecordTypeId==RcdTypId.id) {
      
        For (Case c: newCases) {
        
         //Get old case value to compair new and old values
           Case oldCase = new Case();
           For (Case oc: oldCases) {
             if (oc.id == c.id){
               oldCase = oc;
             }
           }
           
         /*
           1) If Sharing Case With field is blank: add Responding Office to Share and Multi Text.  
           2) If Sharing Case With field does not match old value, set Multi Text to new value.  
           3) If new value does not include Responding Office, Add to Share Case and Mulit Text. 
           4) If there are new Share Case with and new Responding Office, add all values to both.      
          */
           if (c.Share_Case_With__c == null) {
             c.Share_Case_With__c = c.Responding_Office__c;
             c.Multi_Select_Text__c = c.Responding_Office__c;
           }
           else if (c.Share_Case_With__c != oldCase.Share_Case_With__c) {
             if (c.Share_Case_With__c.Contains(c.Responding_Office__c) == False) {
               c.Share_Case_With__c += ';' + c.Responding_Office__c;
             }
             c.Multi_Select_Text__c = c.Share_Case_With__c;
           }
           else if (c.Share_Case_With__c.Contains(c.Responding_Office__c) == False) {
             c.Share_Case_With__c += ';' + c.Responding_Office__c;
             c.Multi_Select_Text__c += ';' + c.Responding_Office__c;
           }
        }
        
       } 
        
      } 
      Catch (Exception e) {
        System.debug('CaseTriggerHelper Error: '+e);
      }
     
    }
  
  
  
  
  
  }