src/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>Closed_User_Stories__c</fullName>
        <inlineHelpText>Stories with status of: Deployed or Rejected.</inlineHelpText>
        <label>Closed User Stories</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_User_Stories__c</fullName>
        <inlineHelpText>Stories with Status other than: Deployed or Rejected.</inlineHelpText>
        <label>Open User Stories</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Stories__c</fullName>
        <label>Total Stories</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Story_Points__c</fullName>
        <inlineHelpText>The total number of story points from all User Stories in the Sprint.</inlineHelpText>
        <label>Total Story Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserStory__c.object
<CustomObject>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move to QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployed to QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move to UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployed to UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move to Prod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <label>Level of Effort</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>34</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>89</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>WK-{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UserStoryTriggerHelper.cls
public with sharing class UserStoryTriggerHelper {

    public static void CalculateUserStoryStats(List<UserStory__c> triggerNew, Map<Id, UserStory__c> triggerOldMap) {
        
        Sprint__c userStorySprint = new Sprint__c ();
        List <Sprint__c> totalSprints = New List <Sprint__c>();
        //ID UserStoryRecTypeID = [Select id from RecordType where name = 'User Story'].id;
        Set <Sprint__c> setSprint = new Set <Sprint__c>();

        //Get all unique sprints represented by stories in the trigger.
        For (UserStory__c us: triggerNew) {
            Sprint__c sprintAdd = new Sprint__c();
            sprintAdd.id = us.Sprint__c;
            if (setSprint.contains(sprintAdd) == False) {
                setSprint.add(SprintAdd);
            }
        } 
        
        For (Sprint__c sp: setSprint) {
            totalSprints.add(sp);
        }

        //System.debug('TotalSprints: ' + totalSprints.size());

        //Get all user stories from all sprints represented in the trigger
        List <UserStory__c> allUserStories = [Select id, Story_Points__c, Sprint__c, Status__c 
            from UserStory__c where Sprint__c in: totalSprints]; //and recordtypeid =: UserStoryRecTypeID];     
 
        //System.debug('allUserStories: ' + allUserStories.size());
        
        //Update User Stories with changed values in the Trigger
        for (UserStory__c aUS: allUserStories) {
            for (UserStory__c tUS: triggerNew) {
                if (aUS.id == tUS.id) {
                    aUS.Story_Points__c = tUS.Story_Points__c;
                    aUS.Status__c = tUS.Status__c;
                }
            }
        }
        
        //Loop through all included Sprints and then all Stories in the Sprint to calculate the values
        for (Sprint__c s: totalSprints) {
            Integer storyPoints = 0;
            Integer totalStories = 0;
            Integer openStories = 0;
            Integer closedStories = 0;
            
            //System.debug('Sprint ID: '+ s.id);
            
            for (UserStory__c us: allUserStories) {
                if (us.Sprint__c == s.id) {
                    //System.debug (' Before - US id: ' + us.id + ' sp: ' + storyPoints + ' CS: ' + closedStories + ' OS: ' + openStories);
                    if (String.isEmpty(us.Story_Points__c) == False) {
                            storyPoints += Integer.valueOf(us.Story_Points__c);
                        }
                        if (us.Status__c == 'Deployed' || us.Status__c == 'Rejected') {
                            closedStories += 1;
                        } 
                        else {
                            openStories += 1;
                        }
                    totalStories += 1;
                    //System.debug (' After - US id: ' + us.id + ' sp: ' + storyPoints + ' CS: ' + closedStories + ' OS: ' + openStories);  
                }
            }
            //System.debug (' END - sp: ' + storyPoints + ' CS: ' + closedStories + ' OS: ' + openStories); 
            s.Total_Story_Points__c = storyPoints;
            s.Total_Stories__c = totalStories;
            s.Closed_User_Stories__c = closedStories;
            s.Open_User_Stories__c = openStories;
            Update s;           
        }

    }
}