src/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserStory__c.object
<CustomObject>
    <fields>
        <fullName>Requester__c</fullName>
        <label>Requester</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move to QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployed to QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move to UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployed to UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move to Prod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <label>Level of Effort</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>34</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>89</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <inlineHelpText>Format: &quot;As a &lt;role&gt;, I want &lt;goal/desire&gt; so that &lt;benefit&gt;.&quot;</inlineHelpText>
        <label>User Story</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>WK-{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UserStoryTriggerHelperTest.cls
@isTest
private class UserStoryTriggerHelperTest {

    static testMethod void testUserStorys() {
        //RecordType usRT = [Select id from RecordType where name = 'User Story'];
        ID profID = [Select id from Profile where name = 'System Administrator'].id;
        User u = new user();
            u.LastName = 'Test Code';
            u.Email = 'test@test.com';
            u.Alias = 'Tcode';
            u.Username = 'test1234444@nist.gov.pc';
            u.CommunityNickname = 'test12'; 
            u.LocaleSidKey = 'en_US';
            u.TimeZoneSidKey = 'GMT';
            u.ProfileID = profID;
            u.LanguageLocaleKey = 'en_US';
            u.EmailEncodingKey = 'UTF-8';
            insert u;

        Sprint__c sprnt = new Sprint__c (name='Sprint', Status__c = 'Not Started', Start_Date__c = date.today(), 
            End_Date__c=system.today().adddays(30)); 
        insert sprnt;
        
        UserStory__c us1 = new UserStory__c (//RecordTypeid=usRT.id, 
        Requester__c=u.id, Sprint__c=sprnt.id, 
            user_story__c='testing user story', Story_Points__c='3');
        insert us1;
        
        UserStory__c us2 = new UserStory__c (//RecordTypeid=usRT.id, 
        Requester__c=u.id, Sprint__c=sprnt.id, 
            user_story__c='testing user story', Story_Points__c='3', Status__c='New');
        insert us2;
       
       
        
    }
}